#-------------------------------
# Site Settings
title: Clint Bird
logo: /images/logo.gif
logo_dark: /images/logo-dark.gif
description: 40 something year old digital / lean enthusiast and aspiring chef. 20+ years experience in operations, supply chain, digitalization, cost reduction and project management.
color_scheme: auto


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'CV'
      url: '/cv/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Business'
      url: '/tags/?tag=business'
    - title: 'Digitalization'
      url: '/tags/?tag=digitalization'
    - title: 'Cooking'
      url: '/tags/?tag=cooking'
    - title: 'Stuff'
      url: '/tags/?tag=stuff'


#-------------------------------
# Hero Settings
hero:
  enable: false
  hero__title: #
  hero__description: #
  hero__image: #


#-------------------------------
# Author Global Settings
author:
  author__name: Clint Bird
  author__bio: 40 something year old digital / lean enthusiast and aspiring chef. 20+ years experience in operations, supply chain, digitalization, cost reduction and project management.
  author__avatar: /images/avatar.gif


#-------------------------------
# Blog Section Settings
blog__settings:
  enable: true
  blog__title: Latest Posts
  blog__description:


#-------------------------------
# Videos Section Settings
videos__settings:
  enable: false
  videos__title: Latest Videos
  videos__description:


#-------------------------------
# Tag Section Settings
tag__settings:
  enable: true
  tag: business


#-------------------------------
# Author Section Settings
author__section:
  enable: false
  author__section__title: Hi, I'm Clint
  author__section__description: A 40 something year old father, husband, lean, digital enthusiast and aspiring chef! Originally from Australia, but due to some of life's unforeseen adventures am now happily settled in Hamburg Germany.<br><br>I'm deeply passionate about lean, technology, continuous improvement, and I love applying these principles to every aspect of my life — whether it's data science, business transformation, or BBQing!<br><br>I've set this site up to act mainly just as a repository of stuff I find interesting & fun - hopefully, others find it the same as well. If you'd like to connect, share a story, or just chat about anything, feel free to explore the site and get in touch.
  aurhor__section__button__text: More About Me
  aurhor__section__button__link: /cv
  author__section__big__image: /images/clint.webp
  author__section__small__image: /images/desk.webp


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  enable: false
  mailchimp__title: #
  mailchimp__description: #
  mailchimp__identifier: # 
  mailchimp__input__text: #
  mailchimp__button__text: #
  mailchimp__background__image: #


#-------------------------------
# Footer Settings
footer__description: A 40 something year old father, husband, lean, digital enthusiast and aspiring chef! Originally from Australia, but due to some of life's unforeseen adventures am now happily settled in Hamburg Germany.<br><br>I'm deeply passionate about lean, technology, continuous improvement, and I love applying these principles to every aspect of my life — whether it's data science, business transformation, or BBQing!<br><br>I've set this site up to act mainly just as a repository of stuff I find interesting & fun - hopefully, others find it the same as well. If you'd like to connect, share a story, or just chat about anything, feel free to explore the site and get in touch.


# Social Links
social:
- {icon: "logo-linkedin", link: "https://linkedin.com/in/clintjb"}
- {icon: "logo-github", link: "https://github.com/clintjb"}
- {icon: "md-headset", link: "https://listenbrainz.org/user/clintjb"}
- {icon: "md-mail", link: "/contact/"}
- {icon: "logo-rss", link: "https://www.clintbird.com/feed.xml"}

# Icons at https://ionicons.com/v4/


# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'CV'
      url: '/about/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Business'
      url: '/tags/?tag=business'
    - title: 'Digitalization'
      url: '/tags/?tag=digitalization'
    - title: 'Cooking'
      url: '/tags/?tag=cooking'
    - title: 'Stuff'
      url: '/tags/?tag=stuff'


#-------------------------------
# Contact Settings
contact:
  email: xjvjyrol
  description: If you'd like to connect, share a story, or just chat about anything, feel free to drop me a line below:


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: clintbird


#-------------------------------
# Google Analytics
google-analytics: G-ZGNEJ3RZ6F
